### ISSUE TITLE
line numbering of code samples does not support copy and paste

### ISSUE THREAD

**Issue by dwcramer** [docbook/docbook.github.io#2]
An advantage of html over pdf is that it's easier to copy code samples from html without getting artefacts like linebreaks added for wrapping or mysterious hidden characters.

I notice that the line numbering feature in the xslts automatically number lines, but do it in such a way that it makes copy and pasting of the code sample impossible. I'd like to add support for the copy-and-paste use case as a requirement for the treatment code samples by the xslts.

Adding a client side highlighter (like SyntaxHighlighter) is an attractive option since it can give you line numbering, highlighting, and a "copy to clipboard" button for free. One challenge, however, is the need to support callouts and other html markup that can be added to code samples. The client side highlighters are confused by this extra markup and highlight it. We did get one of these to work, but it required mucking around in the highlighter's regular expressions and slowed it down considerably (see an example at [2], double click on a code sample to select it). We also investigated pygments, but were having trouble working it into our maven-based build process (not that it would be impossible, but the SyntaxHighlighter was quicker). 

It would be ideal to see a mechanism in the stock stylesheets that support copying of code samples, syntax highlighting, line numbering, and callouts (whether added via <co> elements or areaspec) supported.

Thanks,
David

[1] http://alexgorbatchev.com/SyntaxHighlighter/
[2] http://docs.rackspace.com/auth/api/v2.0/auth-client-devguide/content/Sample_Request_Response-d1e64.html

**Comment by stefanseefeld** [comment]
Hello,
it sounds like this issue would better be filed with the https://github.com/docbook/xslt20-stylesheets repo, wouldn't it ? This current repo is merely a place to publish content either for cdn.docbook.org or docbook.org, and thus arguably shouldn't have an active issue tracker at all.

**Comment by ndw** [comment]
Indeed. David, I think I've now completed the transition to using prism.js for syntax highlighting which hash the features you're looking for. I'm going to remove the issue tracker from this repo.
